### ISSUE TITLE
Peer review 1

### ISSUE THREAD

**Issue by ReimKuos** [katriryt/kanpaiwordgame#1]
### Review 
Generally the app seems to have a good idea and seems to work in its current condition with little to no errors 
 - "sign out" and "sign in" are both on the creen same time, could some conditions be placed so that only one of them is showing at a time, as things that won't do anything at a qiven moment should be hidden to avoid clutter
 - You can see the question data under the question (from which you can get the answer), this might be good to hide (I assume it's for testing purposes) or be printed on the command line
 - The code, of expecially of the **siqnup** -route, is messy could something like password checking be done with an outside function

**Comment by katriryt** [comment]
Thank you for your feedback! 

I implemented sign-out and sign-in to show depending on user status, good idea. Moreover, I added a navigation bar to polish the layout further.

Question data was shown for testing purposes and was removed from the screen in the final version. 

Code was polished for the final version. :)
