### ISSUE TITLE
Vertaisarvio 2

### ISSUE THREAD

**Issue by emigination** [katriryt/kanpaiwordgame#2]
Sovelluksen ulkoasu on selkeä ja käytettävyys erinomainen. Tilastot ovat mielenkiintoinen lisä, tietokantaa on käytetty monipuolisesti ja koodissa nimet ovat kuvaavia. Kaiken kaikkiaan vaikuttaa  todella valmiilta. Sovelluksessa tosin pelisivulla näkyy koko ajan oikea vastaus sekä pari riviä koodia.

Ohjeena oli “noin 5-10” taulua, niin en tiedä onko neljä siltä kannalta riittävästi. Sanojen esiintymisjärjestys olisi hyvä sekoittaa jotenkin, sillä nyt numerot, viikonpäivät jne. tulevat järjestyksessä, niin että arvaaminen on vähän turhan helppoa. Opeteltava sisältö vaikuttaa oikealta, mutta en ehkä alkeistason materiaaliin sisällyttäisi kanjeja sanoille, jotka yleensä kirjoitetaan vain kanalla, kuten あなた ja しょっぱい ;)

**Comment by katriryt** [comment]
Kiitokset palautteesta!

Tauluista todellakin puuttui yksi, joka oli tarkoitettu sessioiden perustietojen tallettamiseen ja sessioiden analysointiin. Lisäsin taulun ja siihen liittyvät statistiikat viimeiseen versioon. 

Sanojen esiintymisjärjestys on tietoisesti valittu niin, että se pysyy samana, koska alkeita opiskellessa sanat on helpompi oppia, kun niitä toistaa samassa järjestyksessä. Ideat ovat kuitenkin erittäin hyviä! Kanjit ovat mukana mausteena, jotta niihin alkaisi tottua. En uskaltautunut vielä tässä vaiheessa omilla japanin taidoilla tekemään valintoja enemmän/vähemmän käytettyjen kanjien välillä, joten jätin sovellukseen kattavan listauksen. Palaute on kuitenkin erittäin tärkeä, tuhannet kiitokset asiantuntevasta palautteesta! :)
